"""Aurora inference Azure Machine Learning (AML) Component definition and deployment.

Simply run this script to create or update the component in an AML workspace.
By default, the workspace parameters (subscription_id, resource_group_name,
workspace_name) are retrieved from temporary environment variables defined in ./.env -
see ./.template.env for details on creating this file.
"""

from azure.ai.ml import Input, Output
from azure.ai.ml.entities import CommandComponent

from setup.common.utils import create_mlclient

if __name__ == "__main__":
    component = CommandComponent(
        name="workshop_aurora_inference",
        description="Component for performing Aurora inference.",
        version="1",
        command=(
            "python -m main "
            "--model ${{inputs.model}} "
            "--data ${{inputs.data}} "
            "--start_datetime ${{inputs.start_datetime}} "
            "--steps ${{inputs.steps}} "
            "--predictions ${{outputs.predictions}}"
        ),
        code="./setup/components/inference/",
        # NOTE: environment does get persisted in registered component
        environment="aurora-inference:1",
        # NOTE: mode and path are stripped from inputs and outputs on registration
        inputs={
            "model": Input(
                type="custom_model",
                description="Pretrained Aurora model checkpoint.",
            ),
            "data": Input(
                type="uri_folder",
                optional=True,
                description=(
                    "Data asset containing the initial state for inference. Leave "
                    "empty for a test run with synthetic data."
                ),
            ),
            "start_datetime": Input(
                type="string",
                description=(
                    "Start ISO 8601 format datetime for initial state data e.g. "
                    "2026-01-01T00:00:00."
                ),
            ),
            "steps": Input(
                type="integer",
                default=1,
                min=1,
                max=10,
                description="Number of autoregressive steps to perform.",
            ),
        },
        outputs={
            "predictions": Output(
                type="uri_file",
                description="NetCDF comprising forecasts generated by each step.",
            ),
        },
        instance_count=1,
        is_deterministic=True,
        # include common utils and constants for use in remote code
        additional_includes=["./setup/components/common/"],
    )
    mlc = create_mlclient(local=True)
    mlc.components.create_or_update(component)
