"""Aurora inference script.

This script takes a set of arguments through the command line to perform autoregressive
forecasting using a pretrained Aurora model. All generated forecasts are written to a
NetCDF file at the specified output path. The final prediction is evaluated against
ground-truth data and relevant metrics and figures are logged with MLflow.

Running locally:
    See notebooks/0_aurora_workshop_local.ipynb for example usage or run:
    `python -m setup.components.inference.main -h`

Running in Azure Machine Learning:
    See setup/components/inference/component.yaml for definition and
    notebooks/0_aurora_workshop.ipynb for example usage. Deploy with
    `az ml component create -f setup/components/inference/component.yaml -w <workspace>
    -g <resource_group>`

For configuration, see examples in notebooks/inference_configs.yaml and the Pydantic
model definition in `setup.components.common.models.InferenceConfig`.
"""

import argparse
from typing import TYPE_CHECKING, cast

import cartopy.crs as ccrs
import matplotlib.pyplot as plt
import mlflow
import torch
import xarray as xr
from aurora import rollout

if TYPE_CHECKING:
    from cartopy.mpl.geoaxes import GeoAxes

# NOTE: enable imports in local and remote environments
# alternatively, use sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))
# and remove the try/except, retaining only the top common import block
try:
    from common.loss import rmse_loss
    from common.models import InferenceConfig
    from common.utils import (
        batch_to_xarray,
        create_logger,
        load_model,
        tz_naive_datetime,
    )
except ImportError:
    from setup.components.common.loss import rmse_loss
    from setup.components.common.models import InferenceConfig
    from setup.components.common.utils import (
        batch_to_xarray,
        create_logger,
        load_model,
        tz_naive_datetime,
    )

LOG = create_logger(__name__)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Aurora Inference")
    parser.add_argument(
        "--model",
        type=str,
        help=(
            "Path to the pre-trained Microsoft Aurora model checkpoint to use in "
            "inference."
        ),
    )
    parser.add_argument(
        "--data",
        type=str,
        help=(
            "Path to the data containing the initial state for inference. Ignored if "
            "configured mode is test."
        ),
    )
    parser.add_argument(
        "--start_datetime",
        type=tz_naive_datetime,
        help=(
            "ISO 8601 format start datetime for initial state data e.g. "
            "2025-01-01T00:00:00. This datetime and that -6 hours must be present in "
            "the data."
        ),
    )
    parser.add_argument(
        "--config",
        type=InferenceConfig.model_validate_json,
        help="JSON-serialised string of inference configuration.",
    )
    parser.add_argument(
        "--predictions",
        type=str,
        help=(
            "Path to which a NetCDF of forecasts generated by each step will be "
            "written."
        ),
    )
    args = parser.parse_args()
    cfg: InferenceConfig = args.config
    LOG.info("Starting inference run with config: %s", cfg.model_dump())

    LOG.info("Loading initial state batch: path=%s", args.data)
    init_batch = cfg.mode.batch_fn(
        data_path=args.data,
        start_datetime=args.start_datetime,
        **cfg.variable_map,
    )
    LOG.info(
        "Loaded initial state batch: times=%s, variables=%s, levels=%s",
        init_batch.metadata.time,
        [*init_batch.surf_vars, *init_batch.atmos_vars, *init_batch.static_vars],
        init_batch.metadata.atmos_levels,
    )

    LOG.info("Loading model: path=%s", args.model)
    model = load_model(args.model, train=False, **cfg.aurora_init_kwargs)
    LOG.info("Loaded model: kwargs=%s", cfg.aurora_init_kwargs)

    LOG.info("Starting inference: start=%s, steps=%d", args.start_datetime, cfg.steps)
    pred = None
    with torch.inference_mode():
        datasets = []
        for pred in rollout(model, init_batch, steps=cfg.steps):
            LOG.info(
                "Inference step complete: %d/%d, timestamp=%s",
                pred.metadata.rollout_step,
                cfg.steps,
                pred.metadata.time[0].isoformat(timespec="hours"),
            )
            datasets.append(batch_to_xarray(pred))
    model = model.to("cpu")

    # pred should never be None here, but guard for pylance
    assert pred is not None, "No predictions generated, skipping write and evaluation."
    LOG.info("Concatenating and writing predictions: path=%s", args.predictions)
    preds_ds = xr.concat(datasets, dim="time")
    preds_ds.to_netcdf(args.predictions)

    LOG.info("Starting evaluation of surface variables.")
    eval_datetime = pred.metadata.time[0]
    LOG.info("Loading target batch: path=%s", args.data)
    tgt_batch = cfg.mode.batch_fn(
        data_path=args.data,
        start_datetime=eval_datetime,
        times=1,
        **cfg.variable_map,
    )
    LOG.info(
        "Loaded target batch: times=%s, variables=%s, levels=%s",
        tgt_batch.metadata.time,
        [*tgt_batch.surf_vars, *tgt_batch.atmos_vars, *tgt_batch.static_vars],
        tgt_batch.metadata.atmos_levels,
    )

    for longname, shortname in cfg.variable_map["surf_vars"].items():
        LOG.info("Starting evaluation: variable=%s", longname)
        target_t = tgt_batch.surf_vars[shortname]
        prediction_t = pred.surf_vars[shortname]

        # compute and log RMSE for the globe
        rmse = rmse_loss(prediction_t, target_t).item()
        LOG.info("RMSE: %.4f", rmse)
        mlflow.log_metric(f"{longname} RMSE", rmse)

        # display difference between prediction and ground truth
        diff_t = (prediction_t - target_t).squeeze().cpu().numpy()
        fig = plt.figure(figsize=(40, 50))
        ax = fig.add_subplot(1, 1, 1, projection=ccrs.PlateCarree())
        ax = cast("GeoAxes", ax)
        extent = (-180., 180., -90., 90.)
        ax.set_extent(extents=extent)
        ax.coastlines()
        ax.gridlines(draw_labels=True)
        im = ax.imshow(
            diff_t,
            origin="upper",
            extent=extent,
            transform=ccrs.PlateCarree(),
            vmin=diff_t.min(),
            vmax=diff_t.max(),
        )
        plt.colorbar(im, ax=ax, orientation="horizontal", pad=0.05, shrink=0.8)
        ax.set_title(
            f"Predicted vs. ground-truth - {longname} - {eval_datetime} - "
            f"{cfg.steps} steps",
        )
        mlflow.log_figure(
            fig,
            f"{longname}_{eval_datetime.isoformat(timespec='hours')}_prediction_error_map.png",
        )
        plt.close(fig)
        LOG.info("Finished evaluation: variable=%s", longname)

    LOG.info("Done!")
