test:
  steps: 4
  mode: test

era5:
  steps: 4
  mode: era5

new_variables_lora:
  steps: 4
  mode: era5
  aurora_config:
    use_lora: true
  extra_variables:
    2m_dewpoint_temperature:
      kind: surf_vars
      key: d2m
