"""Aurora fine-tuning Azure Machine Learning (AML) Component definition.

To create or update the component in your AML workspace, run:
    python -m setup.components.training.component

By default, the workspace parameters (subscription_id, resource_group_name,
workspace_name) are retrieved from temporary environment variables defined in ./.env -
see ./.template.env for details on creating this file.
"""

from azure.ai.ml import Input, Output
from azure.ai.ml.entities import CommandComponent

from setup.common.utils import create_mlclient

if __name__ == "__main__":
    component = CommandComponent(
        name="aurora_finetuning",
        display_name="Aurora Finetuning",
        description="Component for performing fine-tuning with Aurora.",
        version="1",
        command=(
            "python -m main "
            "--model ${{inputs.model}} "
            "--data ${{inputs.data}} "
            "--start_datetime ${{inputs.start_datetime}} "
            "--end_datetime ${{inputs.end_datetime}} "
            # config arg wrapped in single quotes to handle JSON format
            "--config '${{inputs.config}}' "
            "--loss ${{outputs.loss}} "
            "--prediction ${{outputs.prediction}} "
            "--finetuned ${{outputs.finetuned}}"
        ),
        code="./setup/components/training/",
        # environment gets persisted in registered component
        environment="aurora-environment:1",
        # mode and path are stripped from inputs and outputs on registration
        inputs={
            "model": Input(
                type="custom_model",
                description="Pretrained Aurora model checkpoint.",
            ),
            "data": Input(
                type="uri_folder",
                description="Data asset containing the fine-tuning data.",
            ),
            "start_datetime": Input(
                type="string",
                description=(
                    "Start ISO 8601 format datetime e.g. 2025-01-01T00:00:00. "
                    "This datetime and that -6 hours must be present in the data."
                ),
            ),
            "end_datetime": Input(
                type="string",
                description=(
                    "End ISO 8601 format datetime e.g. 2025-01-31T23:00:00. "
                    "This datetime is only possibly used as a target."
                ),
            ),
            "config": Input(
                type="string",
                description="JSON string of fine-tuning configuration.",
            ),
        },
        outputs={
            "loss": Output(
                type="uri_file",
                description="NumPy array (.npy) comprising the loss of each step.",
            ),
            "prediction": Output(
                type="uri_file",
                description=(
                    "NetCDF comprising the forecast generated by the final step."
                ),
            ),
            "finetuned": Output(
                type="uri_file",
                description="Fine-tuned Aurora model checkpoint.",
            ),
        },
        instance_count=1,
        # whether to re-run the component when inputs are the same
        is_deterministic=True,
        # include common utils and constants for use in remote code
        additional_includes=["./setup/components/common/"],
    )
    mlc = create_mlclient(local=True)
    mlc.components.create_or_update(component)
