"""Aurora fine-tuning Azure ML Component definition."""

from azure.ai.ml import Input, Output
from azure.ai.ml.entities import CommandComponent

from setup.common.utils import create_mlclient

if __name__ == "__main__":
    component = CommandComponent(
        name="aurora-finetuning",
        description="Component for performing fine-tuning using with Aurora.",
        version="1",
        command=(
            "python -m main "
            "--model ${{inputs.model}} "
            "--data ${{inputs.data}} "
            "--start_datetime ${{inputs.start_datetime}} "
            "--loss ${{outputs.loss}} "
            "--prediction ${{outputs.prediction}}"
        ),
        code="./setup/components/training/main.py",
        environment="aurora-inference:1",
        inputs={
            "model": Input(
                type="custom_model",
                description="Pretrained Aurora model checkpoint.",
            ),
            "data": Input(
                type="uri_folder",
                optional=True,
                description=(
                    "Data asset containing the fine-tuning data. Leave empty for a "
                    "test run with synthetic data."
                ),
            ),
            "start_datetime": Input(
                type="string",
                description=(
                    "Start ISO 8601 format datetime e.g. 2026-01-01T00:00:00."
                ),
            ),
            "steps": Input(
                type="integer",
                default=1,
                min=1,
                max=10,
                description="Number of autoregressive steps to perform.",
            ),
        },
        outputs={
            "loss": Output(
                type="uri_file",
                description="NumPy array (.npy) comprising the loss of each step.",
            ),
            "prediction": Output(
                type="uri_file",
                description=(
                    "NetCDF comprising the forecast generated by the final step."
                ),
            ),
        },
        instance_count=1,
        is_deterministic=True,
        additional_includes=["./setup/components/common/"],
    )
    mlc = create_mlclient(local=True)
    mlc.components.create_or_update(component)
