"""Aurora fine-tuning Azure Machine Learning (AML) Component definition.

Simply run this script to create or update the component in an AML workspace.
By default, the workspace parameters (subscription_id, resource_group_name,
workspace_name) are retrieved from temporary environment variables defined in ./.env -
see ./.template.env for details on creating this file.
"""

from azure.ai.ml import Input, Output
from azure.ai.ml.entities import CommandComponent

from setup.common.utils import create_mlclient

if __name__ == "__main__":
    component = CommandComponent(
        name="aurora-finetuning",
        description="Component for performing fine-tuning with Aurora.",
        version="1",
        command=(
            "python -m main "
            "--model ${{inputs.model}} "
            "--data ${{inputs.data}} "
            "--start_datetime ${{inputs.start_datetime}} "
            "--type ${{inputs.type}} "
            "--steps ${{inputs.steps}} "
            "--mode ${{inputs.mode}} "
            "--loss ${{outputs.loss}} "
            "--prediction ${{outputs.prediction}}"
        ),
        code="./setup/components/training/",
        # environment gets persisted in registered component
        environment="aurora-inference:2",
        # mode and path are stripped from inputs and outputs on registration
        inputs={
            "model": Input(
                type="custom_model",
                description="Pretrained Aurora model checkpoint.",
            ),
            "data": Input(
                type="uri_folder",
                description="Data asset containing the fine-tuning data.",
            ),
            "start_datetime": Input(
                type="string",
                description=(
                    "Start ISO 8601 format datetime e.g. 2026-01-01T00:00:00."
                ),
            ),
            "type": Input(
                type="string",
                enum=["simple", "lora", "autoregressive"],
                description="Type of fine-tuning to perform.",
            ),
            "steps": Input(
                type="integer",
                min=1,
                max=10,
                description="Number of fine-tuning steps to perform, min 1, max 10.",
            ),
            "mode": Input(
                type="string",
                enum=["eval", "test"],
                description=(
                    "Whether to run in eval mode with real data or test mode with "
                    "synthetic data."
                ),
            ),
        },
        outputs={
            "loss": Output(
                type="uri_file",
                description="NumPy array (.npy) comprising the loss of each step.",
            ),
            "prediction": Output(
                type="uri_file",
                description=(
                    "NetCDF comprising the forecast generated by the final step."
                ),
            ),
        },
        instance_count=1,
        # whether to re-run the component when inputs are the same
        is_deterministic=True,
        # include common utils and constants for use in remote code
        additional_includes=["./setup/components/common/"],
    )
    mlc = create_mlclient(local=True)
    mlc.components.create_or_update(component)
